# Configuration for downloading and uploading data
# Reuters Dataset: https://kdd.ics.uci.edu/databases/reuters21578/reuters21578.html

nltk_corpus: reuters
nltk_corpus_download_dir: test_data
folder_name: "Lorelai Test Data"
drive_service_config: credentials.json
default_evaluator: gpt-3.5-turbo
lorelai_api: http://localhost:5000
data_dir: test_data

question_file: questions.json
question_classes_file: questionclasses.yaml
org_name: "Helixiora"
user_name: "Walter Heck"
