version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    group:
      name: "all"  # Group name for all updates
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    group:
      name: "all"  # Same group name used to combine updates
