repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 24.3.0  # Use the appropriate Black version
    hooks:
      - id: black
        language_version: python3.11  # Specify Python version as per your environment

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0  # Use the appropriate Flake8 version
    hooks:
      - id: flake8
        additional_dependencies: [flake8-black]
