services:
  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mysql:8.4
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_HOST: ${DB_HOST}
      MYSQL_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  llmsherpa:
    image: ghcr.io/nlmatics/nlm-ingestor:latest
    ports:
      - "5010:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  web:
    image: ghcr.io/helixiora/helixiora-lorelai/web:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: web-development
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:${DB_ROOT_PASSWORD}@db:3306/${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - LLMSHERPA_API_URL=http://llmsherpa:5001/api/parseDocument?renderFormat=all
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      llmsherpa:
        condition: service_healthy
    command: gunicorn -w 4 -k gevent --timeout 300 -b 0.0.0.0:5000 --certfile=/app/cert.pem --keyfile=/app/key.pem --reload "run:app"

  worker:
    image: ghcr.io/helixiora/helixiora-lorelai/worker:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: worker-development
    env_file:
      - .env
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql+mysqlconnector://root:${DB_ROOT_PASSWORD}@db:3306/${DB_NAME}
      - REDIS_URL=redis://redis:6379
      - OBJC_DISABLE_INITIALIZE_FORK_SAFETY=1
      - LOG_LEVEL=DEBUG
      - NO_PROXY=*
      - LORELAI_RQ_QUEUES=indexer_queue question_queue default
      - LLMSHERPA_API_URL=http://llmsherpa:5001/api/parseDocument?renderFormat=all&applyOcr=yes
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      llmsherpa:
        condition: service_healthy
    command: rq worker-pool -n 4 indexer_queue question_queue default

volumes:
  redis-data:
  db-data:

networks:
  default:
