"""add password_hash column to user.

Revision ID: b2fbd2224f49
Revises: 2ba475b5b68b
Create Date: 2024-11-21 02:58:45.411182

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00003"
down_revision = "00002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "marked_deleted",
            existing_type=mysql.INTEGER(),
            type_=sa.Boolean(),
            existing_nullable=True,
        )

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("marked_deleted", sa.Boolean(), nullable=True))

    with op.batch_alter_table("datasource", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password_hash", sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    with op.batch_alter_table("datasource", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_column("marked_deleted")

    with op.batch_alter_table("chat_conversations", schema=None) as batch_op:
        batch_op.alter_column(
            "marked_deleted",
            existing_type=sa.Boolean(),
            type_=mysql.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
