"""Plan and google_drive_item url fields added.

Revision ID: 00002
Revises: 00001
Create Date: 2024-11-07 15:54:29.392133

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00002"
down_revision = "00001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database."""
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "google_drive_items", sa.Column("item_url", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "google_drive_items", sa.Column("icon_url", sa.String(length=255), nullable=False)
    )
    op.add_column("plans", sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column(
        "plans", sa.Column("duration_months", mysql.INTEGER(unsigned=True), nullable=False)
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_user_plans_user_id", "user_plans", ["user_id"], unique=False)
    op.create_index("idx_user_plans_plan_id", "user_plans", ["plan_id"], unique=False)
    op.drop_column("plans", "duration_months")
    op.drop_column("plans", "price")
    op.drop_column("google_drive_items", "icon_url")
    op.drop_column("google_drive_items", "item_url")
    # ### end Alembic commands ###
