"""add datasource_id back to indexing_runs.

Revision ID: 00008
Revises: 00007
Create Date: 2025-01-01 23:06:52.662208

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00008"
down_revision = "00007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("indexing_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("datasource_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "datasource", ["datasource_id"], ["datasource_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("indexing_runs", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("datasource_id")

    # ### end Alembic commands ###
