"""add error column to indexing_runs.

Revision ID: 00007
Revises: 00006
Create Date: 2025-01-01 15:59:40.981912

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "00007"
down_revision = "00006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("indexing_runs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("error", sa.Text(), nullable=True))
        batch_op.drop_constraint("indexing_runs_ibfk_1", type_="foreignkey")
        batch_op.drop_column("datasource_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("indexing_runs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("datasource_id", mysql.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            "indexing_runs_ibfk_1", "datasource", ["datasource_id"], ["datasource_id"]
        )
        batch_op.drop_column("error")

    # ### end Alembic commands ###
