"""empty message.

Revision ID: 00012
Revises: 00011
Create Date: 2025-01-30 10:27:16.709661

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "00012"
down_revision: str | None = "00011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.add_column(sa.Column("classified_prompt", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("chat_messages", schema=None) as batch_op:
        batch_op.drop_column("classified_prompt")

    # ### end Alembic commands ###
