name: Build and Push Docker images using /build comment

on:
  issue_comment:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/build') && github.event.issue.pull_request != null && github.event.action == 'created'
    permissions:
      contents: read
      packages: write
      actions: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Get PR branch name
        uses: actions/github-script@v6
        id: get-branch
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pullRequest = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pullRequest.data.head.ref;

      - name: Extract branch name
        id: prep
        run: |
          BRANCH_NAME=$(echo "${{ steps.get-branch.outputs.result }}" | sed 's/\//-/g; s/#//g')
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "Branch Name: $BRANCH_NAME"
          echo "Image Tag: $IMAGE_TAG"
          echo "GITHUB_REF: $GITHUB_REF"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER: $GITHUB_RUN_NUMBER"
          echo "GITHUB_JOB: $GITHUB_JOB"
          echo "GITHUB_ACTION: $GITHUB_ACTION"
          cat $GITHUB_EVENT_PATH

      - name: Build and push web image
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          target: web-production
          push: true
          tags: ghcr.io/${{ github.repository }}/web:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Build and push worker image
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          target: worker-production
          push: true
          tags: ghcr.io/${{ github.repository }}/worker:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Logout from Docker
        run: docker logout ghcr.io

      - name: Post build status to PR comment
        if: always() # Ensure this step runs regardless of job success or failure
        uses: actions/github-script@v6
        with:
          script: |
            const status = context.job === 'success' ? 'succeeded' : 'failed';
            const issueComment = context.payload.comment;
            const runId = process.env.GITHUB_RUN_ID;
            const repoUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}`;
            const buildLogUrl = `${repoUrl}/actions/runs/${runId}`;
            const webImageUrl = `ghcr.io/${context.repo.owner}/${context.repo.repo}/web:${process.env.IMAGE_TAG}`;
            const workerImageUrl = `ghcr.io/${context.repo.owner}/${context.repo.repo}/worker:${process.env.IMAGE_TAG}`;
            github.rest.issues.createComment({
              issue_number: issueComment.issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The build for this branch has ${status}.
              - **Build Log**: [View Logs](${buildLogUrl})
              - **Web Image**: ${webImageUrl}
              - **Worker Image**: ${workerImageUrl}`
            });

      - name: Send final Slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
