name: Build and Push Docker images

on:
  issue_comment:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/build') && github.event.issue.pull_request != null && github.event.action == 'created'
    permissions:
      contents: read
      packages: write
      actions: read
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v2
        id: comment-branch

      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Extract branch name
        id: prep
        run: |
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g; s/#//g')
            echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV
      - name: Build and push web image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository }}/web:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
      - name: Build and push worker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          file: ./Dockerfile.worker
          push: true
          tags: ghcr.io/${{ github.repository }}/worker:${{ env.IMAGE_TAG }}
          platforms: linux/amd64,linux/arm64
      - name: Logout from Docker
        run: docker logout ghcr.io
