name: Build and Push Docker images using /build comment

on:
  issue_comment:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/build') && github.event.issue.pull_request != null && github.event.action == 'created'
    permissions:
      contents: read
      packages: write
      actions: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.issue.pull_request.head.ref }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Extract branch name
        id: prep
        run: |
            BRANCH_NAME=$(echo "${{ github.event.issue.pull_request.head.ref }}" | sed 's/\//-/g; s/#//g')
            echo "IMAGE_TAG=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Build and push web image
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          target: web-production
          push: true
          tags: ghcr.io/${{ github.repository }}/web:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Build and push worker image
        uses: docker/build-push-action@v6.1.0
        with:
          context: .
          file: ./Dockerfile
          target: worker-production
          push: true
          tags: ghcr.io/${{ github.repository }}/worker:${{ env.IMAGE_TAG }}
          platforms: linux/amd64

      - name: Logout from Docker
        run: docker logout ghcr.io

      - name: Post build status to PR comment
        if: always() # Ensure this step runs regardless of job success or failure
        uses: actions/github-script@v6
        with:
          script: |
            const status = context.job === 'success' ? 'succeeded' : 'failed';
            const issueComment = context.payload.comment;
            const runId = process.env.GITHUB_RUN_ID;
            const repoUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}`;
            const buildLogUrl = `${repoUrl}/actions/runs/${runId}`;
            const webImageUrl = `ghcr.io/${context.repo.owner}/${context.repo.repo}/web:${process.env.IMAGE_TAG}`;
            const workerImageUrl = `ghcr.io/${context.repo.owner}/${context.repo.repo}/worker:${process.env.IMAGE_TAG}`;
            github.rest.issues.createComment({
              issue_number: issueComment.issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The build for this branch has ${status}.
              - **Build Log**: [View Logs](${buildLogUrl})
              - **Web Image**: ${webImageUrl}
              - **Worker Image**: ${workerImageUrl}`
            });
