name: Deploy Terraform Apply

on:
  workflow_run:
    workflows: ["Deploy Terraform Plan"]
    types:
      - completed

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v4

    - name: Verify AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws --version

    - name: Checkout Terraform repository
      uses: actions/checkout@v4
      with:
        repository: helixiora/helixiora-terraform
        path: helixiora-terraform
        token: ${{ secrets.GH_PAT }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.3

    - name: Download Plan
      uses: actions/download-artifact@v4.0.0
      with:
        name: tfplan
        path: ./helixiora-terraform/products-lorelai

    - name: Terraform Apply
      working-directory: ./helixiora-terraform/products-lorelai
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_github_token: ${{ secrets.TERRAFORM_GITHUB_TOKEN }}
        TF_VAR_github_username: ${{ secrets.TERRAFORM_GITHUB_USERNAME }}
        TF_VAR_openai_api_key: ${{ secrets.OPENAI_API_KEY }}
        TF_VAR_pinecone_api_key: ${{ secrets.PINECONE_API_KEY }}
        TF_VAR_google_client_id: ${{ secrets.GOOGLE_CLIENT_ID }}
        TF_VAR_google_project_id: ${{ secrets.GOOGLE_PROJECT_ID }}
        TF_VAR_google_client_secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        TF_VAR_google_redirect_uris: ${{ secrets.GOOGLE_REDIRECT_URIS }}
        TF_VAR_lorelai_environment: ${{ secrets.LORELAI_ENVIRONMENT }}
        TF_VAR_lorelai_environment_slug: ${{ secrets.LORELAI_ENVIRONMENT_SLUG }}
        TF_VAR_lorelai_redirect_uri: ${{ secrets.LORELAI_REDIRECT_URI }}
        TF_VAR_db_name: ${{ secrets.DB_NAME }}
        TF_VAR_db_user: ${{ secrets.DB_USER }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      run: terraform apply -auto-approve tfplan
