name: Documentation

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - master
      - mysql-handover # This is for a test, drop when confirmed

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install all dependencies (including pdoc)
      - run: pip install -r requirements.txt
      # Build documentation into docs/
      - run: pdoc *.py lorelai app -o docs/ 
