name: Pre-commit update

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: helixiora/helixiora-lorelai
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run autoupdate
        run: pre-commit autoupdate

      - name: Commit and push
        run: |
          git checkout -b upgrade/pre-commit
          git add .pre-commit-config.yaml
          git commit -m "Upgrade pre-commit dependencies"
          git push origin upgrade/pre-commit

      - name: Authenticate with GitHub CLI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo $GITHUB_TOKEN | gh auth login --with-token

      - name: Open pull request
        run: gh pr create --fill
