name: Pre-commit update

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: helixiora/helixiora-lorelai
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run autoupdate
        run: pre-commit autoupdate

      - name: Commit and push
        run: |
          git checkout -b upgrade/pre-commit || git checkout upgrade/pre-commit
          git add .pre-commit-config.yaml
          git commit -m "Upgrade pre-commit dependencies" || echo "No changes to commit"
          git push origin upgrade/pre-commit || git push --set-upstream origin upgrade/pre-commit

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< $GITHUB_TOKEN
          gh pr create --title "Upgrade pre-commit dependencies" --body "This PR updates the pre-commit dependencies to their latest versions." --base main --head upgrade/pre-commit
